src/astrid/AdBundle/Entity/Photo.php
<?php

namespace astrid\AdBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * Photo
 *
 * @ORM\Table(name="Photo")
 * @ORM\Entity(repositoryClass="astrid\AdBundle\Repository\PhotoRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Photo
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="url", type="string", length=255, unique=false, nullable=true)
     */
    private $url;

    /**
     * @var string
     *
     * @ORM\Column(name="alt", type="string", length=255, nullable=true)
     */
    private $alt;


    private $file;

    private $tempFilename;

    /**
     * @ORM\ManyToOne(targetEntity="Advert", inversedBy="photos")
     */
    private $advert;


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set url
     *
     * @param string $url
     *
     * @return Photo
     */
    public function setUrl($url)
    {
        $this->url = $url;

        return $this;
    }

    /**
     * Get url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Set alt
     *
     * @param string $alt
     *
     * @return Photo
     */
    public function setAlt($alt)
    {
        $this->alt = $alt;

        return $this;
    }

    /**
     * Get alt
     *
     * @return string
     */
    public function getAlt()
    {
        return $this->alt;
    }



    public function setFile(UploadedFile $file)
    {
        $this->file = $file;

        // On vérifie si on avait déjà un fichier pour cette entité
        if (null !== $this->url) {
          // On sauvegarde l'extension du fichier pour le supprimer plus tard
          $this->tempFilename = $this->url;

          // On réinitialise les valeurs des attributs url et alt
          $this->url = null;
          $this->alt = null;
        }
    }

    public function getFile()
    {
        return $this->file;
    }

    /**
     * Set advert
     *
     * @param \astrid\AdBundle\Entity\Advert $advert
     *
     * @return Photo
     */
    public function setAdvert(\astrid\AdBundle\Entity\Advert $advert = null)
    {
        $this->advert = $advert;

        return $this;
    }

    /**
     * Get advert
     *
     * @return \astrid\AdBundle\Entity\Advert
     */
    public function getAdvert()
    {
        return $this->advert;
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function preUpload()
    {
    // Si jamais il n'y a pas de fichier (champ facultatif), on ne fait rien
        if (null === $this->file) {
          return;
        }

        // Le nom du fichier est son id, on doit juste stocker également son extension
        // Pour faire propre, on devrait renommer cet attribut en « extension », plutôt que « url »
        $this->url = $this->file->guessExtension();

        // Et on génère l'attribut alt de la balise <img>, à la valeur du nom du fichier sur le PC de l'internaute
        $this->alt = $this->file->getClientOriginalName();
    }

    /**
    * @ORM\PostPersist()
    * @ORM\PostUpdate()
    */
    public function upload()
    {

        if (null === $this->file) {
        return;
        }

        if (null !== $this->tempFilename) {
            $oldFile = $this->getUploadRootDir().'/'.$this->id.'.'.$this->tempFilename;
            if (file_exists($oldFile)) {
                unlink($oldFile);
            }
        }


        $this->file->move(
        $this->getUploadRootDir(),
        $this->id.'.'.$this->url
        );
    }

    /**
    * @ORM\PreRemove()
    */
    public function preRemoveUpload()
    {
        
        $this->tempFilename = $this->getUploadRootDir().'/'.$this->id.'.'.$this->url;
    }

    /**
    * @ORM\PostRemove()
    */
    public function removeUpload()
    {

        if (file_exists($this->tempFilename)) {

        unlink($this->tempFilename);
        }
    }

    public function getUploadDir()
    {

    return 'uploads/img';
    }

    protected function getUploadRootDir()
    {

    return __DIR__.'/../../../../web/'.$this->getUploadDir();
    }

}

src/astrid/AdBundle/Resources/views/add.html.twig
{# src/astrid/AdBundle/Resources/views/index.html.twig #}

{% extends "astridAdBundle::layout.html.twig" %}

{% block title %}
  Home
{% endblock %}

{% block body %}

  <h2>Write a new ad</h2>

<div class="well">
  {{ form_start(form, {'attr': {'class': 'form-horizontal'}}) }}
  {{ form_errors(form) }}


  <div class="form-group">
    {# Génération du label. #}
    {{ form_label(form.title, "Title", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}

    {# Affichage des erreurs pour ce champ précis. #}
    {{ form_errors(form.title) }}

    <div class="col-sm-10">
      {# Génération de l'input. #}
      {{ form_widget(form.title, {'attr': {'class': 'form-control'}}) }}
    </div>
  </div>

  {# Idem pour un autre champ. #}
  <div class="form-group">
    {{ form_label(form.description, "Advert Description", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}
    {{ form_errors(form.description) }}
    <div class="col-sm-10">
      {{ form_widget(form.description) }}
    </div>
  </div>

   <div class="form-group">
    {{ form_label(form.photos, "Add photos", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}
    {{ form_errors(form.photos) }}
    <div class="col-sm-10">
      {{ form_widget(form.photos) }}
      <br><a id="add_pictures" class="btn btn-primary" > Add a picture</a>
    </div>
  </div>

  <div class="form-group">
    {{ form_label(form.category, "Category:", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}
    {{ form_errors(form.category) }}
    <div class="col-sm-10">
      {{ form_widget(form.category) }}
    </div>
  </div>

  <div class="form-group">
    {{ form_label(form.city, "City:", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}
    {{ form_errors(form.city) }}
    <div class="col-sm-10">
      {{ form_widget(form.city) }}
    </div>
  </div>

  <div class="form-group">
    {{ form_label(form.price, "Price:", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}
    {{ form_errors(form.price) }}
    <div class="col-sm-10">
      {{ form_widget(form.price) }}
    </div>
  </div>

  {% for file in form.photos %}

{{ form_errors(file) }} {{ form_widget(file) }}


{% endfor %}

  {# Pour le bouton, pas de label ni d'erreur, on affiche juste le widget #}
  {{ form_widget(form.save, {'attr': {'class': 'btn btn-primary'}}) }}

  {# Génération automatique des champs pas encore écrits.
     Dans cet exemple, ce serait le champ CSRF (géré automatiquement par Symfony !)
     et tous les champs cachés (type « hidden »). #}
  {{ form_rest(form) }}

  {# Fermeture de la balise <form> du formulaire HTML #}
  {{ form_end(form) }}
</div>

<script>
	$('#add_pictures').click(function(){
    var total_files=$("#member_pictures_container li").length;
    var file_label=document.createElement("label");
    file_label.innerHTML="File";
    file_label.for="PhotoAndDescription_files_"+total_files;
    var div_file=document.createElement("div");    
    div_file.appendChild(file_label);
    var picture= document.createElement('input');
    picture.name="PhotoAndDescription[files]["+total_files+"][file]";
    picture.type="file";
    picture.id="PhotoAndDescripton_files_"+total_files;
    div_file.appendChild(picture);
    div_container=document.createElement('div');
    div_container.id="PhotoAndDescription_files_"+total_files;
    div_container.appendChild(div_file);
    var list_element=document.createElement('li');
    list_element.appendChild(div_container);
    $('#member_pictures_container').append(list_element);
});

</script>
{% endblock %}

src/astrid/AdBundle/Resources/views/delete.html.twig
{# src/astrid/AdBundle/Resources/views/index.html.twig #}

{% extends "astridAdBundle::layout.html.twig" %}

{% block title %}
  Deleting {{ advert.title }}
{% endblock %}

{% block body %}

  <h2> Deleting {{ advert.title }} </h2>


<p> Are you sure you want to delete this ad ? </p>

 <form action="{{ path('astrid_ad_delete', {'id': advert.id}) }}" method="post">
    <a href="{{ path('astrid_ad_view', {'id': advert.id}) }}" class="btn btn-default">
      <i class="glyphicon glyphicon-chevron-left"></i>
      Go back to the ad.
    </a>

    <input type="submit" value="Delete" class="btn btn-danger" />

    {{ form_rest(form) }}
  </form>

{% endblock %}

src/astrid/AdBundle/Resources/views/deletephoto.html.twig
{# src/astrid/AdBundle/Resources/views/index.html.twig #}

{% extends "astridAdBundle::layout.html.twig" %}

{% block title %}
  Deleting photo
{% endblock %}

{% block body %}

  <h2> Deleting photo </h2>


<p> Are you sure you want to delete this photo ? </p>

<img
		  src="{{ asset(photo.uploadDir ~ '/' ~ photo.id ~ '.' ~ photo.url) }}"
		  alt="{{ photo.alt }}" style="width:300px; height: auto;"
		/>

 <form action="{{ path('astrid_ad_deletephoto', {'id': photo.id}) }}" method="post">
    <a href="{{ path('astrid_ad_edit', {'id': advert.id}) }}" class="btn btn-default">
      <i class="glyphicon glyphicon-chevron-left"></i>
      Go back to the ad.
    </a>

    <input type="submit" value="Delete" class="btn btn-danger" />

    {{ form_rest(form) }}
  </form>

{% endblock %}

src/astrid/AdBundle/Resources/views/edit.html.twig
{# src/astrid/AdBundle/Resources/views/index.html.twig #}

{% extends "astridAdBundle::layout.html.twig" %}

{% block title %}
  Home
{% endblock %}

{% block body %}

  <h2>Write a new ad</h2>

<div class="well">
  {{ form_start(form, {'attr': {'class': 'form-horizontal'}}) }}
  {{ form_errors(form) }}


  <div class="form-group">
    {# Génération du label. #}
    {{ form_label(form.title, "Title", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}

    {# Affichage des erreurs pour ce champ précis. #}
    {{ form_errors(form.title) }}

    <div class="col-sm-10">
      {# Génération de l'input. #}
      {{ form_widget(form.title, {'attr': {'class': 'form-control'}}) }}
    </div>
  </div>

  {# Idem pour un autre champ. #}
  <div class="form-group">
    {{ form_label(form.description, "Advert Description", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}
    {{ form_errors(form.description) }}
    <div class="col-sm-10">
      {{ form_widget(form.description) }}
    </div>
  </div>

  <div class="well">
  {% for photo in advert.photos %}
    <img
      src="{{ asset(photo.uploadDir ~ '/' ~ photo.id ~ '.' ~ photo.url) }}"
      alt="{{ photo.alt }}" style="width:200px; height: auto;"
    />
    <a href=" {{ path('astrid_ad_deletephoto', {'id': photo.id}) }} " class="btn btn-danger" ><span class="glyphicon glyphicon-minus-sign" ></span> </a>

  {% endfor %}
</div>

  {% if form.photos is defined %}
   <div class="form-group">
    {{ form_label(form.photos, "Add photos", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}
    {{ form_errors(form.photos) }}
    <div class="col-sm-10">
      {{ form_widget(form.photos) }}
    </div>
  </div>
{% endif %}


  <div class="form-group">
    {{ form_label(form.category, "Category:", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}
    {{ form_errors(form.category) }}
    <div class="col-sm-10">
      {{ form_widget(form.category) }}
    </div>
  </div>

  <div class="form-group">
    {{ form_label(form.city, "City:", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}
    {{ form_errors(form.city) }}
    <div class="col-sm-10">
      {{ form_widget(form.city) }}
    </div>
  </div>

  <div class="form-group">
    {{ form_label(form.price, "Price:", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}
    {{ form_errors(form.price) }}
    <div class="col-sm-10">
      {{ form_widget(form.price) }}
    </div>
  </div>

  {% if form.photos is defined %}
    {% for file in form.photos %}

      {{ form_errors(file) }} {{ form_widget(file) }}
    {% endfor %}
  {% endif %}

  {# Pour le bouton, pas de label ni d'erreur, on affiche juste le widget #}
  {{ form_widget(form.save, {'attr': {'class': 'btn btn-primary'}}) }}

  {# Génération automatique des champs pas encore écrits.
     Dans cet exemple, ce serait le champ CSRF (géré automatiquement par Symfony !)
     et tous les champs cachés (type « hidden »). #}
  {{ form_rest(form) }}

  {# Fermeture de la balise <form> du formulaire HTML #}
  {{ form_end(form) }}
</div>

<script>

</script>


{% endblock %}

src/astrid/AdBundle/Resources/views/home.html.twig
{# src/astrid/AdBundle/Resources/views/index.html.twig #}

{% extends "astridAdBundle::layout.html.twig" %}

{% block title %}
  Home
{% endblock %}

{% block body %}

  <h2>Welcome to MyAds</h2>
  <h3> Please enter a city and a category...</h3>

{{ form_start(form) }}
    {{ form_errors(form) }}

    {{ form_row(form.city) }}
    {{ form_row(form.category) }}

    {{ form_row(form.Search) }}
{{ form_end(form) }}

<h3> ... or write a new ad!</h3>

<a href="{{ path('astrid_ad_new') }}" class="btn btn-success btn-sm"><span class="glyphicon glyphicon-plus"></span> Add advert</a>

{% endblock %}

src/astrid/AdBundle/Resources/views/index.html.twig
{# src/astrid/AdBundle/Resources/views/index.html.twig #}

{% extends "astridAdBundle::layout.html.twig" %}

{% block title %}
  Advert index 
{% endblock %}

{% block body %}

  <h2> Adverts in {{ city.name }} and in the {{ category.name }}  category :</h2>


{% for advert in ads %} 
	<p> <a href="{{ path('astrid_ad_view', {'id': advert.id}) }}" ><strong>{{ advert.title}} </strong></a> {{ advert.date|date('d/m/Y')}} <a href="{{ path('astrid_ad_edit', {'id': advert.id}) }} " class="btn btn-sm btn-warning" >Edit this ad</a> <a href="{{ path('astrid_ad_delete', {'id': advert.id}) }}" class="btn btn-sm btn-danger">Delete</a></p> 

{% endfor %}

{% endblock %}

src/astrid/AdBundle/Resources/views/layout.html.twig
{# src/OC/CoreBundle/Resources/views/Admin/layout.html.twig #}

<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" type="text/css" />
    <title>MyAds - {% block title %}{% endblock %}</title>
</head>
<body>
    {% block bodyempty %}
    <div class="container">
        <nav class="navbar navbar-default navbar-fixed-top navbar-inverse" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-target">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{{ path('astrid_ad_homepage') }}">MiniCMS</a>
                </div>
                <div class="collapse navbar-collapse" id="navbar-collapse-target">
                </div>
            </div><!-- /.container -->
        </nav>
        <div id="body" style="margin-top:70px;" >{% block body %}{% endblock body %}</div>
        
    </div>
{% endblock bodyempty %}
    {% block javascripts %}
    {# Ajoutez ces lignes JavaScript si vous comptez vous servir des fonctionnalités du bootstrap Twitter #}
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  {% endblock %}

</body>
</html>

src/astrid/AdBundle/Resources/views/view.html.twig
{# src/astrid/AdBundle/Resources/views/view.html.twig #}

{% extends "astridAdBundle::layout.html.twig" %}

{% block title %}
  {{ advert.title }}
{% endblock %}

{% block body %}

  <h2> {{ advert.title }} </h2>



<div class="well"> 
	<p> {{ advert.description |raw}} </p> 
	<span class = "label"> {{ advert.price }} </span> <br>
	<strong> {{ advert.city.name}} </strong> <br>
	<strong> {{ advert.category.name }} </strong>
</div>
<div class="well">
	{% for photo in advert.photos %}
		<img
		  src="{{ asset(photo.uploadDir ~ '/' ~ photo.id ~ '.' ~ photo.url) }}"
		  alt="{{ photo.alt }}" style="width:200px; height: auto;"
		/>

	{% endfor %}
</div>


{% endblock %}